### ISSUE TITLE
FYI Regarding Discussion About Toggling Flow Launcher via Flow.Launcher.exe

### ISSUE THREAD

**Issue by EnigmaSolved** [AminSallah/Flow.Launcher.Plugin.WinHotkey#1]
Just wanted you to be in the loop regarding a discussion I'm having regarding making it possible to toggle Flow via `Flow.Launcher.exe` which _in theory_ might be better in the long run than your code having to invoke the `Alt-Space` hotkey (which then in turn invokes the toggling of Flow). Of course, you don't have to change anything on your end if you don't want to -- just wanted you to be aware of potential future options. :)

https://github.com/Flow-Launcher/Flow.Launcher/issues/2586

**Comment by AminSallah** [comment]
Thanks @EnigmaSolved for involving me. WinHotkey using simulate alt+space for some points
- flow hooks into the entire Keyboard Keys and waiting for hotkey to pressed and it's trigger by KeyDown and don't wait for KeyUp to trigger. theoretically offering a faster triggering and eliminate delay of trigger but using shell to run flow using `%localappdata%\FlowLauncher\Flow.Launcher.exe` it's wait for commond to be excuted to trigger which means a little delay may be not noticeable but it is not bettter as trigger by KeyDown.

- Alt+space is a unique shortcut for launcher apps and not used for any other app to the best of my knowledge, Therefore, simulating it is not a big deal.
- WinHotkey trigger delay because is waiting for KeyUp then determine if trigger flow or release LWin button.

Let me know if you have different point.

**Comment by EnigmaSolved** [comment]
I think those are all valid points. I had been wondering if running `Flow.Launcher.exe` (to toggle) would have been faster, but I think you are right that it probably will be slightly slower. So yeah, nothing to change after all! I appreciate you engaging in the conversation, though, and thank you for creating your plugin! :)
